### ISSUE TITLE
Is a caching layer necessary?

### ISSUE THREAD

**Issue by eliseumds** [adamazad/bildx#1]
Nowadays it's easy to setup a CDN in front of your origin server with AWS CloudFront, Google Cloud CDN, Azure CDN or Cloudflare, for example, so I wonder if caching the images in Redis is necessary.

**Comment by adamazad** [comment]
Hi Eliseu! That was one solution. I agree; computed images are cached in `cache` storage, but I/O and Nodejs are not that friendly. I rather put a caching layer in front of BildX when I use it.
